<?php

namespace App\Repository\Entity;

/**
 * Email_has_tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Email_has_tagRepository extends \Doctrine\ORM\EntityRepository
{
}
