<?php

namespace App\Repository\Entity;

/**
 * MasterIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
