<?php

namespace App\Repository\Entity;

/**
 * Verified_emailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Verified_emailRepository extends \Doctrine\ORM\EntityRepository
{
}
